# Generated by Django 4.2.16 on 2024-09-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_to_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publication'),
        ),
    ]
