# Generated by Django 4.2.16 on 2024-09-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_image_image_alter_image_image_to_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_to_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.publication'),
        ),
    ]
