# Generated by Django 4.2.16 on 2024-09-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_comment_com_author_alter_comment_com_to_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
