# Generated by Django 4.2.16 on 2024-09-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_comment_com_to_pub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinate',
            old_name='coor',
            new_name='coor_text',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='coor_adres',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='coor_coordinates',
            field=models.CharField(blank=True, null=True),
        ),
    ]
