# Generated by Django 4.2.16 on 2024-09-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_coor_coordinate_coor_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='coor_to_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='app.publication'),
        ),
    ]
