# Generated by Django 4.2.16 on 2024-10-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pub_coor_adress',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_coor_coordinates',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_coor_text',
            field=models.CharField(blank=True, null=True),
        ),
    ]
