# Generated by Django 4.2.16 on 2024-10-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_publication_pub_coor_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='pub_coor_adress',
            new_name='coor_adress',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_coor_coordinates',
            new_name='coor_coordinates',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_coor_text',
            new_name='coor_text',
        ),
    ]
